archive = "bionic"
version = "18.04"
origin = "system76"
label = "System76"
email = "info@system76.com"

[[source]]
name = "system76-cuda"
build_on = "changelog"
assets = [
    { src = "nvidia_cuda/*", dst = "debian"}
]

[[source]]
name = "system76-cuda-9.0"
build_on = "changelog"
keep_source = false
retain = 1
assets = [
    { src = "cuda_makefile", dst = "Makefile" },
    { src = "nvidia_cuda/*", dst = "debian"}
]

[[source]]
name = "system76-cuda-9.2"
build_on = "changelog"
keep_source = false
retain = 1
assets = [
    { src = "cuda_makefile", dst = "Makefile" },
    { src = "nvidia_cuda/*", dst = "debian"}
]

[[source]]
name = "system76-cuda-10.0"
build_on = "changelog"
keep_source = false
retain = 1
assets = [
    { src = "cuda_makefile", dst = "Makefile" },
]

[[source]]
name = "system76-cudnn-9.0"
build_on = "changelog"
assets = [
    { src = "nvidia_cuda/*", dst = "debian"}
]
keep_source = false
retain = 1


[[source]]
name = "system76-cudnn-9.2"
build_on = "changelog"
assets = [
    { src = "nvidia_cuda/*", dst = "debian"}
]
retain = 1
keep_source = false

[[source]]
name = "system76-cudnn-10.0"
build_on = "changelog"
assets = [
    { src = "nvidia_cuda/*", dst = "debian"}
]
retain = 1
keep_source = false

[[source]]
name = "system76-cuda-10.1"
build_on = "changelog"
keep_source = false
retain = 1
assets = [
    { src = "cuda_makefile_v2", dst = "Makefile" },
]

[[source]]
name = "system76-cudnn-10.1"
build_on = "changelog"
assets = [
    { src = "nvidia_cuda/*", dst = "debian"}
]
retain = 1
keep_source = false

# Build system required by tensorflow
[[source]]
name = "bazel"
build_on = "changelog"

    [source.location]
    url = "https://github.com/bazelbuild/bazel/releases/download/0.15.0/bazel-0.15.0-dist.zip"
    checksum = "c3b716e6625e6b8c323350c95cd3ae0f56aeb00458dddd10544d5bead8a7b602"

[[source]]
name = "tensorflow-1.9-cuda-9.2"
build_on = "changelog"
retain = 1
assets = [
    { src = "tensorflow-1.9/*", dst = "." },
    { src = "tensorflow/*", dst = "debian" }
]
depends = [
    "bazel",
    "system76-cuda",
    "system76-cuda-9.2",
    "system76-cudnn-9.2",
]

[[source]]
name = "tensorflow-1.9-cpu"
build_on = "changelog"
retain = 1
assets = [
    { src = "tensorflow-1.9/*", dst = "." },
    { src = "tensorflow/*", dst = "debian" }
]
depends = [ "bazel" ]
